### ISSUE TITLE
Can't join to GSoC slack channel

### ISSUE THREAD

**Issue by begeistert** [chipsalliance/ideas#1]
# GSoC Slack Channel

## Brief explanation

Hi! @kgugala! I was reviewing the project Ideas and I'm interested on work with the `FPGA chips database visualizer improvements`, but I'm not able to join the slack channel, and I can't find any other communication channel.

## Expected results

Be able to join the slack channel.

# Detailed Explanation

Following the slack URL, and trying to join I get a problem saying I'm not able to create an account to join the channel (it says I need an email from linuxfoundation.org)

**Comment by Myrausman** [comment]
I am facing the same issue

**Comment by mithro** [comment]
@kgugala / @mgielda - Any idea?

**Comment by Myrausman** [comment]
Thank you,
I tried again from another link and i can join now.

**Comment by pgielda** [comment]
Would be great is someone pasted the link that works, the one that does not work, and where each one was found. We probably have an outdated link somewhere, and up-to-date link somewhere else and we would have to fix that.

**Comment by harshkhandeparkar** [comment]
Any update on this one? I am facing the same issue. The slack invite requires an `@linuxfoundation.org` email address.

**Comment by Myrausman** [comment]
for me following link worked : https://slack-invite.chipsalliance.org/

**Comment by pgielda** [comment]
Both https://f4pga.readthedocs.io/en/latest/community.html#communication and https://www.chipsalliance.org/getting-started/ seem to point to this link.
Where is the wrong link and how does it look like?

**Comment by harshkhandeparkar** [comment]
![image](https://user-images.githubusercontent.com/34770591/222971253-e2d833c0-b97f-4c40-b7cb-ba052841fcaa.png)
It only accepts a `@linuxfoundation.org` email.

**Comment by pgielda** [comment]
This screenshot is the login page not the Sign up page that you get when you use the invite? (also it says "or" so your statement is not true either way...)

**Comment by harshkhandeparkar** [comment]
It is the signup page. And the google/apple sign up doesnt work.
